spring:
  application:
    name: youtube-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 7001
  servlet:
    context-path: /
  shutdown:  graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    path: log/${spring.application.name}/${POD_NAME:local_dev}

yt-dl:
  retry: ${YT_DL_RETRY:3}

minio:
  endpoint: ${MINIO_ENDPOINT}
  credentials:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}