spring:
  application:
    name: youtube-service

server:
  port: 7001
  servlet:
    context-path: /
  shutdown:  graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    path: logs

yt-service:
  env: ${YT_SERVICE_ENV:dev}

yt-dl:
  retry: ${YT_DL_RETRY:3}