spring:
  application:
    name: youtube-service

server:
  port: 7001
  servlet:
    context-path: /youtube-service
  shutdown:  graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

yt-service:
  env: ${YT-ENV:dev}

yt-dl:
  retry: ${YT-DL_RETRY:3}

ffmpeg:
  path: ${FFMPEG_PATH:D:\yt-dlp\ffmpeg-5.0.1-essentials_build\bin\ffmpeg}