replicaCount: 1

image:
  repository: wecgwm/youtube-service
  pullPolicy: Always
  tag: "master"

podLabels:
  metrics: enable

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

server:
  port: 7001
  contextPath: /

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: YT_DLP_PATH
    value: yt-dlp
  - name: MINIO_ENDPOINT
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: MINIO_ENDPOINT
  - name: MINIO_ACCESS_KEY
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: MINIO_ACCESS_KEY
  - name: MINIO_SECRET_KEY
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: MINIO_SECRET_KEY
  - name: YT_CHANNEL_ID
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: YT_CHANNEL_ID
  - name: YT_SCHEDULE_ENABLE
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: YT_SCHEDULE_ENABLE
  - name: YT_SCAN_CRON
    valueFrom:
      configMapKeyRef:
        name: java-config
        key: YT_SCAN_CRON

#envFrom:
#  - secretRef:
#      name:  java-secret

volumeMounts:
  - mountPath: /application/log
    name: log-volume

volumes:
  - name: log-volume
    hostPath:
      path: /usr/local/log
      type: Directory


resources:
  limits:
    cpu: 800m
    memory: 800Mi
  requests:
    cpu: 200m
    memory: 300Mi

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 7001

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}